version: '3'

services:
  db:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
        - '5432:5432'
    volumes:
      - postgres13:/var/lib/postgresql/data

  redis:
    image: redis:7.0.15-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data  

  web:
    container_name: api_rails
    build: .
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails
    depends_on:
      - db
      - redis

volumes:
  postgres13:
  redis_data:

